### ISSUE TITLE
Android 1.0.1 Release Checklist

### ISSUE THREAD

**Issue by g19-mr** [g19-mr/azh#84]
- [x] Update Splash screen screenshot on PlayStore [Only for Phone]
- [x] Point GA to Release Property ID 
- [x] Point Google Maps to Release Key
- [x] Update Build versionName to 1.0.1
- [x] Update VersionCode to 2

**Comment by g19-mr** [comment]
Update 1.0.1 released on Jan 1, 2015.
