### ISSUE TITLE
Android 2.0.0 Release Checklist

### ISSUE THREAD

**Issue by g19-mr** [g19-mr/azh#86]
- [ ] Update Splash screen screenshot on PlayStore [Only for 7-inch tablet]
- [ ] Point GA to Release Property ID 
- [ ] Point Google Maps to Release Key
- [ ] Update Build versionName to 2.0.0
